# Generated by Django 6.0.4 on 2026-08-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
