# Generated by Django 6.0.4 on 2026-08-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0002_leave_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='casual_leave',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='staff',
            name='earned_leave',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='staff',
            name='sick_leave',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
